baseURL = 'https://github.com/KaterynaChernetska/hugo-blog-test.git'
languageCode = 'en-us'
title = 'My New Hugo Site'



[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About Us"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 3
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4